/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chorddetect;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Davex
 */
public class JFrame extends javax.swing.JFrame {

    private Conexion c;

    /**
     * Creates new form JFrame
     *
     * @param conexion
     */
    public JFrame(Conexion conexion) {
        c = conexion;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameNotas = new javax.swing.JFrame();
        jComboBoxNotas = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jComboBoxNotasName = new javax.swing.JComboBox();
        jLabelNameNote = new javax.swing.JLabel();
        jFrameChord = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxChord = new javax.swing.JComboBox();
        jLabelNotesChord = new javax.swing.JLabel();
        jComboBoxChordName = new javax.swing.JComboBox();
        jLabelChordName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxNote1 = new javax.swing.JComboBox();
        jComboBoxNote2 = new javax.swing.JComboBox();
        jComboBoxNote3 = new javax.swing.JComboBox();
        jComboBoxNote4 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabelchordName = new javax.swing.JLabel();
        jFrameTonality = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxTonalityNames = new javax.swing.JComboBox();
        jLabelNotesTonalityNames = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxChord1 = new javax.swing.JComboBox();
        jComboBoxChord2 = new javax.swing.JComboBox();
        jComboBoxChord3 = new javax.swing.JComboBox();
        jComboBoxChord4 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabelchordTonSearch = new javax.swing.JLabel();
        jComboBoxChord5 = new javax.swing.JComboBox();
        jComboBoxChord6 = new javax.swing.JComboBox();
        jComboBoxChord7 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonNotas = new javax.swing.JButton();
        jButtonAcordes = new javax.swing.JButton();
        jButtonTonalidades = new javax.swing.JButton();

        jComboBoxNotas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxNotas.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jComboBoxNotasCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jComboBoxNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNotasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Notas");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabelName.setText("Do");

        jComboBoxNotasName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxNotasName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNotasNameActionPerformed(evt);
            }
        });

        jLabelNameNote.setText("C");

        javax.swing.GroupLayout jFrameNotasLayout = new javax.swing.GroupLayout(jFrameNotas.getContentPane());
        jFrameNotas.getContentPane().setLayout(jFrameNotasLayout);
        jFrameNotasLayout.setHorizontalGroup(
            jFrameNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameNotasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrameNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jFrameNotasLayout.createSequentialGroup()
                        .addGroup(jFrameNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxNotasName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jFrameNotasLayout.createSequentialGroup()
                                .addComponent(jComboBoxNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jFrameNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jFrameNotasLayout.createSequentialGroup()
                                .addComponent(jLabelNameNote, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))))
                .addContainerGap())
        );
        jFrameNotasLayout.setVerticalGroup(
            jFrameNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameNotasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jFrameNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrameNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNotasName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNameNote))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Acordes");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jComboBoxChord.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxChord.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jComboBoxChordCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jComboBoxChord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxChordActionPerformed(evt);
            }
        });

        jLabelNotesChord.setText("C");

        jComboBoxChordName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxChordName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxChordNameActionPerformed(evt);
            }
        });

        jLabelChordName.setText("Do Mayor");

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Formar Acordes");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jComboBoxNote1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxNote2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxNote3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxNote4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Seleccione las notas:");

        jButton1.setText("Formar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Acorde Formado:");

        jLabelchordName.setText("------------------------");

        javax.swing.GroupLayout jFrameChordLayout = new javax.swing.GroupLayout(jFrameChord.getContentPane());
        jFrameChord.getContentPane().setLayout(jFrameChordLayout);
        jFrameChordLayout.setHorizontalGroup(
            jFrameChordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jFrameChordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrameChordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jFrameChordLayout.createSequentialGroup()
                        .addGroup(jFrameChordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxChord, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxChordName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFrameChordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrameChordLayout.createSequentialGroup()
                                .addComponent(jLabelChordName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(jLabelNotesChord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jFrameChordLayout.createSequentialGroup()
                        .addGroup(jFrameChordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jFrameChordLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelchordName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jFrameChordLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxNote1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxNote2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxNote3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxNote4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jFrameChordLayout.setVerticalGroup(
            jFrameChordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameChordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jFrameChordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxChord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNotesChord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrameChordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxChordName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelChordName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrameChordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNote1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxNote2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxNote3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxNote4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrameChordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelchordName))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tonalidades");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jComboBoxTonalityNames.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTonalityNames.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jComboBoxTonalityNamesCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jComboBoxTonalityNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTonalityNamesActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Encontrar Tonalidad");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jComboBoxChord1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxChord2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxChord3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxChord4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Seleccione los acordes:");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel10.setText("Tonalidades Encontradas: ");

        jLabelchordTonSearch.setText("------------------------");

        jComboBoxChord5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxChord6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxChord7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jFrameTonalityLayout = new javax.swing.GroupLayout(jFrameTonality.getContentPane());
        jFrameTonality.getContentPane().setLayout(jFrameTonalityLayout);
        jFrameTonalityLayout.setHorizontalGroup(
            jFrameTonalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameTonalityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrameTonalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrameTonalityLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jFrameTonalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrameTonalityLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelchordTonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jFrameTonalityLayout.createSequentialGroup()
                                .addComponent(jComboBoxChord1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxChord2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxChord3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxChord4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxChord5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxChord6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxChord7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonBuscar))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrameTonalityLayout.createSequentialGroup()
                        .addGroup(jFrameTonalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrameTonalityLayout.createSequentialGroup()
                                .addComponent(jComboBoxTonalityNames, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNotesTonalityNames, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jFrameTonalityLayout.setVerticalGroup(
            jFrameTonalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameTonalityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jFrameTonalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTonalityNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNotesTonalityNames))
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrameTonalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxChord1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxChord2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxChord3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxChord4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxChord5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxChord6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxChord7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrameTonalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelchordTonSearch))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chord Detect");

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chord Detect");

        jButtonNotas.setText("Notas");
        jButtonNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNotasActionPerformed(evt);
            }
        });

        jButtonAcordes.setText("Acordes");
        jButtonAcordes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcordesActionPerformed(evt);
            }
        });

        jButtonTonalidades.setText("Tonalidades");
        jButtonTonalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTonalidadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAcordes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTonalidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNotas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAcordes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTonalidades)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcordesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcordesActionPerformed
        // TODO add your handling code here:
        jFrameChord.setVisible(true);
        jFrameChord.setBounds(0, 0, 500, 255);
        ComboBoxModel<String> cbm = new DefaultComboBoxModel<>(c.getNameChords());
        jComboBoxChord.setModel(cbm);
        ComboBoxModel<String> cbm2 = new DefaultComboBoxModel<>(c.getChords());
        jComboBoxChordName.setModel(cbm2);

        //modificar los array para que tenga un espacio vacio
        String[] notasTmp = c.getNotes();
        String[] notasFinal = new String[notasTmp.length + 1];
        notasFinal[0] = "";
        for (int i = 1; i < notasFinal.length; i++) {
            notasFinal[i] = notasTmp[i - 1];
        }

        //notas para los selectores
        ComboBoxModel<String> cbmNotes1 = new DefaultComboBoxModel<>(notasTmp);
        ComboBoxModel<String> cbmNotes2 = new DefaultComboBoxModel<>(notasTmp);
        ComboBoxModel<String> cbmNotes3 = new DefaultComboBoxModel<>(notasTmp);
        ComboBoxModel<String> cbmNotes4 = new DefaultComboBoxModel<>(notasFinal);

        jComboBoxNote1.setModel(cbmNotes1);
        jComboBoxNote2.setModel(cbmNotes2);
        jComboBoxNote3.setModel(cbmNotes3);
        jComboBoxNote4.setModel(cbmNotes4);
    }//GEN-LAST:event_jButtonAcordesActionPerformed

    private void jButtonNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNotasActionPerformed
        // TODO add your handling code here:
        jFrameNotas.setVisible(true);
        jFrameNotas.setBounds(0, 0, 400, 155);
        ComboBoxModel<String> cbm = new DefaultComboBoxModel<>(c.getNotes());
        jComboBoxNotas.setModel(cbm);
        ComboBoxModel<String> cbm2 = new DefaultComboBoxModel<>(c.getNotesNames());
        jComboBoxNotasName.setModel(cbm2);
    }//GEN-LAST:event_jButtonNotasActionPerformed

    private void jComboBoxNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNotasActionPerformed
        // TODO add your handling code here:
        String position = (String) jComboBoxNotas.getSelectedItem();
        String noteName = c.getNoteName(position);
        jLabelName.setText(Useful.restCharacter(noteName));
    }//GEN-LAST:event_jComboBoxNotasActionPerformed

    private void jComboBoxNotasCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBoxNotasCaretPositionChanged

    }//GEN-LAST:event_jComboBoxNotasCaretPositionChanged

    private void jComboBoxNotasNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNotasNameActionPerformed
        // TODO add your handling code here:
        String position = (String) jComboBoxNotasName.getSelectedItem();
        String noteName = c.getNote(position);
        jLabelNameNote.setText(Useful.restCharacter(noteName));
    }//GEN-LAST:event_jComboBoxNotasNameActionPerformed

    private void jComboBoxChordCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBoxChordCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxChordCaretPositionChanged

    private void jComboBoxChordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxChordActionPerformed
        // TODO add your handling code here:t
        String position = (String) jComboBoxChord.getSelectedItem();
        String chordName = c.getChord(position);
        String[] notesForChord = c.getNotesForChord(Useful.restCharacter(chordName));
        notesForChord = notesForChord[1].split("-");
        chordName += " notas: ";
        for (String string : notesForChord) {
            chordName += string + " ";
        }
        jLabelNotesChord.setText(chordName);
    }//GEN-LAST:event_jComboBoxChordActionPerformed

    private void jComboBoxChordNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxChordNameActionPerformed
        // TODO add your handling code here:
        String position = (String) jComboBoxChordName.getSelectedItem();
        String chordName = c.getChordName(position);
        String[] notesForChord = c.getNotesForChord(position);
        notesForChord = notesForChord[1].split("-");
        chordName += " notas: ";
        for (String string : notesForChord) {
            chordName += string + " ";
        }
        jLabelChordName.setText(chordName);
    }//GEN-LAST:event_jComboBoxChordNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String note1 = (String) jComboBoxNote1.getSelectedItem();
        String note2 = (String) jComboBoxNote2.getSelectedItem();
        String note3 = (String) jComboBoxNote3.getSelectedItem();
        String note4 = (String) jComboBoxNote4.getSelectedItem();

        String[] notes;
        if (note4.isEmpty()) {
            notes = new String[3];
            notes[0] = note1;
            notes[1] = note2;
            notes[2] = note3;
        } else {
            notes = new String[4];
            notes[0] = note1;
            notes[1] = note2;
            notes[2] = note3;
            notes[3] = note4;
        }
        String[] chord = c.getChordForNotes(notes);
        jLabelchordName.setText(chord[1]);
        if (chord[1].isEmpty()) {
            jLabelchordName.setText("Notas no validas");
        } else {
            jLabelchordName.setText(Useful.restCharacter(chord[1]) + ", cifrado: " + Useful.restCharacter(chord[0]));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxTonalityNamesCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBoxTonalityNamesCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTonalityNamesCaretPositionChanged

    private void jComboBoxTonalityNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTonalityNamesActionPerformed
        // TODO add your handling code here:
        String chords = c.getTonalitysChords((String)jComboBoxTonalityNames.getSelectedItem());
        jLabelNotesTonalityNames.setText(chords);
    }//GEN-LAST:event_jComboBoxTonalityNamesActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonTonalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTonalidadesActionPerformed
        // TODO add your handling code here:
        jFrameTonality.setVisible(true);
        jFrameTonality.setBounds(0, 0, 640, 255);
        ComboBoxModel<String> cbm = new DefaultComboBoxModel<>(c.getTonalitysName());
        jComboBoxTonalityNames.setModel(cbm);
        ComboBoxModel<String> cbm2 = new DefaultComboBoxModel<>(c.getChords());
        jComboBoxChordName.setModel(cbm2);
    }//GEN-LAST:event_jButtonTonalidadesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAcordes;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonNotas;
    private javax.swing.JButton jButtonTonalidades;
    private javax.swing.JComboBox jComboBoxChord;
    private javax.swing.JComboBox jComboBoxChord1;
    private javax.swing.JComboBox jComboBoxChord2;
    private javax.swing.JComboBox jComboBoxChord3;
    private javax.swing.JComboBox jComboBoxChord4;
    private javax.swing.JComboBox jComboBoxChord5;
    private javax.swing.JComboBox jComboBoxChord6;
    private javax.swing.JComboBox jComboBoxChord7;
    private javax.swing.JComboBox jComboBoxChordName;
    private javax.swing.JComboBox jComboBoxNotas;
    private javax.swing.JComboBox jComboBoxNotasName;
    private javax.swing.JComboBox jComboBoxNote1;
    private javax.swing.JComboBox jComboBoxNote2;
    private javax.swing.JComboBox jComboBoxNote3;
    private javax.swing.JComboBox jComboBoxNote4;
    private javax.swing.JComboBox jComboBoxTonalityNames;
    private javax.swing.JFrame jFrameChord;
    private javax.swing.JFrame jFrameNotas;
    private javax.swing.JFrame jFrameTonality;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelChordName;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNameNote;
    private javax.swing.JLabel jLabelNotesChord;
    private javax.swing.JLabel jLabelNotesTonalityNames;
    private javax.swing.JLabel jLabelchordName;
    private javax.swing.JLabel jLabelchordTonSearch;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
